apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  - kind: User
    name: system:serviceaccount:default:pod-reader
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  labels:
    app: wallet
spec:
  selector:
    matchLabels:
      app: wallet
  replicas: 0
  template:
    metadata:
      labels:
        app: wallet
    spec:
      serviceAccountName: pod-reader
      containers:
        - name: wallet
          image: "wallet:latest"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: remoting
              containerPort: 2552
          readinessProbe:
            httpGet:
              path: "ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
#          resources:
#            limits:
#              cpu: 1
#              memory: 1G
#            requests:
#              cpu: 100m
#              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wallet
spec:
  selector:
    app: wallet
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
    - port: 2552
      protocol: TCP
      targetPort: remoting
      name: remoting
    - port: 8558
      protocol: TCP
      targetPort: management
      name: management
---


