apiVersion: v1
kind: Namespace
metadata:
  name: wallet
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
  namespace: wallet
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: wallet
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
  namespace: wallet
subjects:
  - kind: User
    name: system:serviceaccount:wallet:pod-reader
    namespace: wallet
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet
  namespace: wallet
  labels:
    app: wallet
spec:
  selector:
    matchLabels:
      app: wallet
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: wallet
    spec:
      serviceAccountName: pod-reader
      containers:
        - name: wallet
          image: "erwincdl/scala-akka-sharding:latest"
          ports:
            - name: http
              containerPort: 8080
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: remoting
              containerPort: 2552
          readinessProbe:
            httpGet:
              path: "ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
#          resources:
#            limits:
#              cpu: 1
#              memory: 1G
#            requests:
#              cpu: 100m
#              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: wallet
  namespace: wallet
spec:
  selector:
    app: wallet
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
      name: http
    - port: 2552
      protocol: TCP
      targetPort: remoting
      name: remoting
    - port: 8558
      protocol: TCP
      targetPort: management
      name: management
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorMapping
metadata:
  name: wallet-mapping
  namespace: wallet
spec:
  hostname: wallet.incubator.10pines.com
  prefix: /
  service: wallet:8080
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: wallet-cert
  namespace: ambassador
spec:
  domains:
    - wallet.incubator.10pines.com